[PICOCOM]
stop = kill $(ps aux | grep '[d]ev/ttyACMX' | awk '{print $2}')
start = picocom -b 115200 /dev/ttyACMX > /tmp/picocom.log 2>&1

[Settings]


; HOST = [  {'ip': '10.230.28.64', 'hostname': 'lm-302-17-s2', 'login': 'remlab', 'password': '1001SMT!', 'picocom': '0','eeprom': 'eeprom-SBBPH28X076TGF_MC0B271.bin', 'pita': '1'}]

HOST = [
    {'ip': '10.230.28.149', 'hostname': 'lm-302-04-s2', 'login': 'remlab', 'password': '1001SMT!', 'picocom': '1','eeprom': 'eeprom-SBBPH28X019TGF_MC0B271.bin', 'pita': '0'},
    {'ip': '10.230.27.88', 'hostname': 'lm-302-05-s2', 'login': 'remlab', 'password': '1001SMT!', 'picocom': '1','eeprom': 'eeprom-SBBPH28X038TGF_MC0B271.bin', 'pita': '0'},
    ; {'ip': '10.230.28.62', 'hostname': 'lm-302-12-s2', 'login': 'remlab', 'password': '1001SMT!', 'picocom': '0','eeprom': 'eeprom-SBBPH28X038TGF_MC0B271.bin', 'pita': '1'},
    {'ip': '10.230.28.64', 'hostname': 'lm-302-17-s2', 'login': 'remlab', 'password': '1001SMT!', 'picocom': '0','eeprom': 'eeprom-SBBPH28X076TGF_MC0B271.bin', 'pita': '1'},
    ; {'ip': '10.230.29.207', 'hostname': 'lm-302-24-s2', 'login': 'remlab', 'password': '1001SMT!', 'picocom': '0','eeprom': 'eeprom-SBBPH28X076TGF_MC0B271.bin', 'pita': '1'},
    {'ip': '10.74.134.101', 'hostname': 'vc-ps-fit-chewy-15', 'login': 'remlab', 'password': '1001SMT!', 'picocom': '2','eeprom': 'eeprom-SBBPH28X153TGF_MC0B271.bin', 'pita': '0'}
    ]


[FW-PREP]
command1 = echo "************** Recovery process started **********************************************"
command2 = cd /home/remlab/Desktop/Dediprog-latest/SF100Linux; sudo ./dpcmd -z /mnt/udrive/ozeabalx/ps-bootprofile/eeprom/eeprom-XXXXXXXXX.bin
command3 = export PYTHONPATH='/home/remlab/bhb_tools/lib'; python -c "from pylib.drive_power import pita; pita.PITA('/dev/ttyACMX').powerCycle()"
command4 = lspci | grep -i Non-Volatile
command5 = sleep 20
command6 = cd /home/jenkins/repos/ent_ssd_test; sudo ["driver-override=uio_pci_generic"] lib/spdk/scripts/setup.sh; sleep 20 
command7 = cd /home/jenkins/repos/ent_ssd_test; sudo ["driver-override=uio_pci_generic"] lib/spdk/scripts/setup.sh reset
command8 = sleep 20
command9 = cd /home/jenkins/repos/ent_ssd_test; sudo ["driver-override=uio_pci_generic"] lib/spdk/scripts/setup.sh
command10 = echo -e "selectdev 1\ntc-unlock\ntc-cdm\ntc-llf\nexit" > /home/remlab/cmdline.cfg
command11 = sudo nvme reset /dev/nvme0; sudo modprobe -r nvme; sudo modprobe nvme;  lsmod | grep nvme
command12 = cd /home/jenkins/repos/ent_ssd_test/spdktest; sudo ./spdktest -t -l /home/remlab/cmdline.cfg > /tmp/spdk.txt
command13 = export PYTHONPATH='/home/remlab/bhb_tools/lib'; python -c "from pylib.drive_power import pita; pita.PITA('/dev/ttyACMX').powerCycle()"
command14 = sleep 20
command15 = rm -r /home/remlab/cmdline.cfg
command16 = lspci | grep -i Non-Volatile
command17 = sleep 20
command18 = cd /home/jenkins/repos/ent_ssd_test; sudo ["driver-override=uio_pci_generic"] lib/spdk/scripts/setup.sh reset
command19 = export PYTHONPATH='/home/remlab/bhb_tools/lib'; python -c "from pylib.drive_power import pita; pita.PITA('/dev/ttyACMX').powerCycle()"
command20 = sleep 20
command21 = cd /home/jenkins/repos/ent_ssd_test; sudo ["driver-override=uio_pci_generic"] lib/spdk/scripts/setup.sh reset
command22 = echo "************** Recovery process ended **********************************************"

[RESTART]
command1 = sudo reboot

[DEDIPROG]
command1 = cd /home/remlab/Desktop/Dediprog-latest/SF100Linux; sudo ./dpcmd -e
command2 = export PYTHONPATH='/home/remlab/bhb_tools/lib'; python -c "from pylib.drive_power import pita; pita.PITA('/dev/ttyACMX').powerCycle()"
command3 = sleep 20