version: '3.3'

services:
  ubuntu:
    image: vinothzeabalane/ps-ubuntu:v3
    hostname: seyon_ollama
    container_name: seyon_ai
    ports:
      - "6070:6070"    # Flask app port
      - "11430:11434"  # Exposing Ollama's port
    volumes:
      - /home/remlab/ps-bpt/PythonAI/platform-ai:/data
    networks:
      - ubuntu-network
    restart: unless-stopped
    command: ["/bin/bash", "-c", "tail -f /dev/null"]

networks:
  ubuntu-network:
    driver: bridge
