version: '3.3'

services:
  web:
    image: odoo:17.0
    container_name: docker_odoo_ts
    hostname: ps-odoo-ts-server
    depends_on:
      - db
    ports:
      - "8059:8069"
    volumes:
      - odoo-ts-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo
      - zeabalane_odoo:/usr/lib/python3/dist-packages/odoo  # Mount the Odoo source

    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo  # Directly setting the password here
    networks:
      - odoo-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    container_name: docker_postgres_ts
    hostname: ps-postgres-ts-server
    ports:
      - "5452:5432"  # Ensure this line is present
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo  # Directly setting the password here
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-ts-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  odoo-ts-web-data:
  odoo-ts-db-data:
  zeabalane_odoo:

networks:
  odoo-network:
    driver: bridge
